### ISSUE TITLE
Question: should we introduce pandas_datareader in pandas-input.md?

### ISSUE THREAD

**Issue by spencerlyon2** [NYUDataBootcamp/Book#13]
In [this section](https://github.com/NYUDataBootcamp/Book/blob/master/pandas-input.md#data-input-3--apis) of the pandas-input.md chapter we go over how to use the API methods from `pandas.io` to read in data from FRED, IMF, and others.

That code has been deprecated in pandas for some time and users are told to use the `pandas_datareader` package.

Eventually the deprecated code will be deleted altogether from pandas and we'll be forced to use `pandas_datareader` to read in the data.

I think the obvious answer is that we should use the currently suggested method here instead of the deprecated routines, but this brings up the issue of using conda to install a package that doesn't come with Anaconda -- something we haven't talked about at this point in the book.

What do people think? Should we take the time to talk about pip and conda before this section (maybe at the start of this lecture in our discussion on packages) so we can use pandas_datareader?

**Comment by cc7768** [comment]
Related to this:

We need to go through and change all of the `import pandas.io.data as web` to the new correct imports from `pandas-datareader`.

**Comment by cc7768** [comment]
Addressed by https://github.com/NYUDataBootcamp/Book/pull/22#pullrequestreview-5888600
