### ISSUE TITLE
Packing imports and conda/pip

### ISSUE THREAD

**Issue by cc7768** [NYUDataBootcamp/Book#15]
Package importing is currently covered in `pandas-input.md`, but it might make sense to break that out since it isn't directly related to inputting data.

We might take the conda/pip material and the package material and make a new chapter between `pyfun-2` and `pandas-input`. This would allow us to introduce them to these ideas and how to install/update packages all at once.

**Comment by spencerlyon2** [comment]
:+1: We should do this.

**Comment by cc7768** [comment]
Closing as this was taken care of by #17
